{% set name = "mapwidget" %}
{% set version = "0.2.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapwidget-{{ version }}.tar.gz
  sha256: 2ad8abf07eeb4813ceda440552a43afe368dd1d686ede3e710c331f039440cff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - anywidget
    - xyzservices

test:
  imports:
    - mapwidget
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/mapwidget
  summary: Custom Jupyter widgets for creating interactive maps
  license: MIT
  license_file: LICENSE
  description: Custom Jupyter widgets for creating interactive maps with popular JavaScript mapping libraries, such as Cesium, Mapbox, MapLibre, Leaflet, and OpenLayers.
  doc_url: https://mapwidget.gishub.org
  dev_url: https://github.com/opengeos/mapwidget

extra:
  recipe-maintainers:
    - giswqs
